---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Пользователь должен зарегистрироваться или быть залогиненным в системе
  - При регистрации пользователя поле номера телефона является обязательным к заполнению
  - При оформлении заказа информация о заказе и пользователе должна уходить к менеджменту
  - Для русской версии интернет-магазина все наименования товаров (кроме брендов) и их описание должно быть на русском языке 
  - Для русской версии интернет-магазина валюта должна быть в рублях
  - На сайте должно быть пользовательское соглашение, соглашение о конфиденциальности и информация о юридическом лице
